### ISSUE TITLE
Support showing browser tabs (preferably Arc, cuz who cares about other browsers) 

### ISSUE THREAD

**Issue by dudunato** [godbout/Wooshy.docs#148] opened 2024-01-31 15:32 UTC
That's all!

**Comment by godbout** [comment] 2024-02-01 17:33
can't believe this dumbtard posted in the wrong repo...

**Comment by godbout** [comment] 2024-03-02 05:18
closing because:
1. wrong repo. this is supposed to go there: https://github.com/godbout/WooshyWindowToTheForeground
2. author of the issue is from Brazil caralho

**Closed by godbout** 2024-03-02 05:18 UTC
