### ISSUE TITLE
Not working on Xero.com, an accounting software

### ISSUE THREAD

**Issue by aaronrolls** [godbout/Wooshy.docs#5] opened 2022-07-25 10:23 UTC
To be fair, nether Homerow, Shortcat or Vimac work 100% on this website. 

Wooshy does not work at all. It detects nothing.

The only keyboard navigation software that has worked fully on Xero is tridactyl, a Firefox extension. But tridactyl has a tendency to overcompensate. 

The browser I tested the website in was Safari.

**Comment by godbout** [comment] 2022-07-25 10:29
man you're killing Wooshy 😅️😂️

i guess that's not on the site itself, but once i create an account and log in?

**Comment by aaronrolls** [comment] 2022-07-25 10:34
Hahaha, I really like it on the whole. It looks like it has more potential than its competition. I’ll be using it a lot so I may be reporting some more in the future. 🙂

And yes, it is the Accounting software itself, not the main page.

I believe you can sign up for a demo account for free.

**Comment by godbout** [comment] 2022-07-25 10:40
> Hahaha, I really like it on the whole. It looks like it has more potential than its competition.

i guess it's gonna be about tastes. i prefer typing something i know i wanna type rather than deciphering two or three letters. brain fog for me. friction. but it may not be for everyone. also as you saw, different apps target different stuff, so sometimes you have more targets but it's slower. hard to balance. i thought about adding something later in the Preferences, to let people choose what they actually wanna target. but not sure. i don't like much options as a user myself. i want the devs to do the hard work for me, not for me to have to think and make choices.

> I’ll be using it a lot so I may be reporting some more in the future. 🙂

please do so. hopefully your reports will help us make Ws better.

> And yes, it is the Accounting software itself, not the main page.
>  > I believe you can sign up for a demo account for free.  

i guessed so but i wanted to ask just in case it was about the site and i could close this issue ☹️

**Comment by aaronrolls** [comment] 2022-07-26 20:54
Wooshy 1a3 is working considerably better on Xero.com than before. It is detecting most fields but it is still struggling with menus. It can click on the menu and open it, but it won't detect the menu items once the menu is open.

These are the menu buttons:

![CleanShot2022-07-27at08 45 38](https://user-images.githubusercontent.com/47949221/181108747-f30796e5-25b1-4efc-9104-f9c7b836edb2.png)

This is the accessibility info for the menu button "Business":

![CleanShot2022-07-27at08 47 11](https://user-images.githubusercontent.com/47949221/181109074-1ca6e250-9411-4124-9753-f031972da1a2.png)

This is what the menu looks like after it has been opened:

![CleanShot2022-07-27at08 49 06](https://user-images.githubusercontent.com/47949221/181109263-1996c6af-ba9c-4aab-805a-6b9b22d5eb32.png)

This is the accessibility info for the menu item "Invoices":

![CleanShot2022-07-27at08 51 05](https://user-images.githubusercontent.com/47949221/181109768-dc982da9-8ccc-433d-8a5b-8396c81f5ba9.png)

**Comment by godbout** [comment] 2022-07-27 02:19
thanks, that's great. haven't opened an account yet coz the trial is of course limited. so when i do i need to focus on this particularly. planning for this year tho.

**Comment by godbout** [comment] 2022-08-08 17:09
ok so i've tried and it seems to work in most places except for those shit menus?

**Comment by godbout** [comment] 2022-08-08 17:44
ok i'm finding the issue. it's a little tricky. no wonder other apps don't find the menu either. for whatever reason there's a combination of wrong number of children returned + API call error. should be hackable, but i need to be careful not to slow things down elsewhere. let's see.

**Comment by godbout** [comment] 2022-08-09 08:38
support for Xero will be added in a14. but it's experimental and may be removed later. i've been trying manually a bunch of webpages and Electron apps and it seems to be ok, but if it breaks other apps/webpages later i'll have to remove this. this is somehow Xero being funky with the AX.

**Comment by aaronrolls** [comment] 2022-08-09 22:42
Hmmmm.... Is it not possible to have Wooshy change its behaviour per website or app? That would be pretty useful.

**Comment by godbout** [comment] 2022-08-10 03:40
lol even that is insane for me. of course you could have different engines on a per website basis. but doesn't that sound crazy? there's already something done on a per app basis, that's as far as i will go. already needed to keep an App Catalog, which is needed for kV anyways but that's gonna be it. for Xero the issue is that the site returns a children count of 0, while there are actually children. as far as i'm concerned this is an issue with the site. bad AX info is gonna happen most frequently with sites and Electron app, cost they do the fuck they want.

**Comment by godbout** [comment] 2022-08-10 08:06
handled in a14: https://github.com/godbout/Wooshy.docs/releases/tag/1.a14

**Comment by aaronrolls** [comment] 2022-08-10 21:34
Thanks for all the work you put in to a14.

I was thinking that the core engine would not change per app of website but different modules or attachments would change. But I don't know how it has been set up.

Unfortunately, I did not notice any difference with a14 as apposed to a13. So if the new additions are slowing other things down, I would remove them. 90% of the stuff is being targeted anyway. I can work with that.

**Comment by godbout** [comment] 2022-08-11 01:48
> Unfortunately, I did not notice any difference with a14 as apposed to a13.

what do you mean? Xero menus still not working? it's working here. or are you talking about another part of the site that i'm not aware of?

https://user-images.githubusercontent.com/121373/184051468-6cc2363c-ff95-42df-8ef9-3f0abf5c7f16.mp4

**Comment by godbout** [comment] 2022-08-11 01:49
> So if the new additions are slowing other things down, I would remove them

i may slow down sites that are badly built. haven't experienced it yet so i think it's good.

**Comment by godbout** [comment] 2022-08-11 02:01
huh, but that's the web right? how could they give me an older version? 😅️

can you show the AI for that menu?

**Comment by godbout** [comment] 2022-08-11 02:04
what i need to see if the `List`:
![Screenshot 2022-08-11 at 10 03 22](https://user-images.githubusercontent.com/121373/184052858-1deb86d2-066a-4f9f-8cef-0d797b75c160.png)
![Screenshot 2022-08-11 at 10 03 42](https://user-images.githubusercontent.com/121373/184052864-606a82e1-05b8-41b5-9b10-d1c3a7ed6d1f.png)

**Comment by godbout** [comment] 2022-08-11 02:07
ok so there's a very good reason why it doesn't work on your end. it seems i didn't ship that change 😂️
or something else, i don't know. i'm trying a14 downloaded from the site and indeed i can't grab the menus. shame.

**Comment by aaronrolls** [comment] 2022-08-11 02:10
> ok so there's a very good reason why it doesn't work on your end. it seems i didn't ship that change 😂️
> or something else, i don't know. i'm trying a14 downloaded from the site and indeed i can't grab the menus. shame.

Ah, ok that makes sense. I've done that before myself. Regardless, here is the info you requested.

Here is the "Business" Button.
![CleanShot2022-08-11at14 03 38](https://user-images.githubusercontent.com/47949221/184052998-f041c99e-ee2d-4e43-a9cc-ad8e63e741aa.png)

Here is the "Invoices" item on the list
![CleanShot2022-08-11at14 06 18](https://user-images.githubusercontent.com/47949221/184053182-b4c3616a-3df7-4fc9-81df-a8d45a497800.png)

The List
![CleanShot2022-08-11at14 08 39](https://user-images.githubusercontent.com/47949221/184053358-d805fce3-5d60-4af9-a8c5-663af867e44b.png)

**Comment by godbout** [comment] 2022-08-11 02:17
thanks.

yeah confirmed. i forgot to tag a new version of the AX Engine. releasing is hard ☹️

will be in a15. (hopefully 🤞️)

**Comment by godbout** [comment] 2022-08-11 11:07
ok if i didn't fuck up it's there now: https://github.com/godbout/Wooshy.docs/releases/tag/1.a15
(no joke allowed)

**Closed by godbout** 2022-08-11 11:07 UTC
