### ISSUE TITLE
not working on Dock when hidden

### ISSUE THREAD

**Issue by blackketter** [godbout/Wooshy.docs#37] opened 2022-07-29 14:48 UTC
If the dock is set to auto-hide and is hidden, Wooshy shows some targets along the edge of the screen for dock items.  

Those targets are not functional.

At a minimum, Wooshy should not show targets that don't work.   

If Dock support is turned it might be neat if Wooshy could unhide the doc to show any valid dock targets.

**Comment by godbout** [comment] 2022-07-29 16:55
personally i put the Dock for fun, but it doesn't make much sense to use Wooshy for it. like it's way faster with a launcher like Alfred. so i'm curious. any reason why using Wooshy over a better tool for that? are there some items that only Wooshy can get? personally i have it off. (in Wooshy, and as auto-hide by macOS.)

**Comment by blackketter** [comment] 2022-07-29 17:08
I like to think of Wooshy as a mouse replacement and the dock an important part of the Mac interface.  I'd use it, especially in the case of restoring minimized windows.

In the short term, it's a cosmetic issue, showing targets that don't work at the edge of the screen when the dock is hidden.

**Comment by godbout** [comment] 2022-07-29 17:17
> especially in the case of restoring minimized windows.

fair. makes sense. launcher can't grab those. cool.

> In the short term, it's a cosmetic issue, showing targets that don't work at the edge of the screen when the dock is hidden.

on which OS are you? Ventura? it used to work on Monterey actually. kinda. if you had the magnifier option you would have some issues if an icon was magnified, because the Accessibility returns the position of the non magnified icon. but click was being done, and apps would open.

i think that make sense not to target if it's hidden, and/or to show it if you click the option. no idea if there's API to "force" this onto the user. but worth checking it yeah. thanks.

**Comment by godbout** [comment] 2022-08-23 15:02
> If Dock support is turned it might be neat if Wooshy could unhide the doc to show any valid dock targets.

so i've spent the day on this. thought it'd be cool yeah. here's the issues tho:
1. there's two ways to manipulate the Dock 1) change it UserDefault settings and kill it. it's slow and the menu bar blinks 2) go through AppleScript and AppleEvents. this is doable but required a bunch of entitlements and it requires the user to accept some macOS permissions blah blah blah. ugly, but doable.
2.  in both cases written above, you can't control how long it takes for the Dock to show. if you ping for the UI Elements before it finished showing, you're out of luck. see the video below:

https://user-images.githubusercontent.com/121373/186192746-8fff5ae1-e2e9-4da3-87da-91d88006fe89.mp4

at first i'm launching Wooshy on Xcode. it takes enough time so that the Dock has time to slide in. then i ping the UI Elements, and it's all good. then i launch Wooshy on the Desktop. it's super fast, too fast for the Dock to slide in. when pinging the UI Elements, macOS returns the old position. because it's cached, you can't get the new position (if it wasn't cached, you'd have to recalculate the whole thing at every keystroke).

there's several dirty ways to handle this. like i could have a timer for when i hide Wooshy, so that it doesn't hide the Dock right away. then you show Wooshy again, and then you'll be able to the latest positions. feels like a very bad hack.

what about if you asked the search scope to include the Dock, we always show it?

**Comment by godbout** [comment] 2022-08-23 15:03
> there's several dirty ways to handle this. like i could have a timer for when i hide Wooshy, so that it doesn't hide the Dock right away. then you show Wooshy again, and then you'll be able to the latest positions. feels like a very bad hack.

no timer, but a very quick show/hide:



https://user-images.githubusercontent.com/121373/186193310-e232aea3-fa0e-4ddc-82dd-638cad661ee2.mp4

**Comment by blackketter** [comment] 2022-08-23 15:36
Wow, thanks for the effort!

What about moving the cursor to unhide the dock?  (Not sure if that’ll even work…)  Then move it back if Wooshy doesn’t execute a click.

And it does seems reasonable that if the user has checked the Dock button that the dock be always shown when Wooshy is invoked.  

When Wooshy does force the dock to be visible, defer the scanning and display of Dock targets until the Dock is visible.   

I mean, if the user has the Dock option turned on, it seems reasonable to slow down Wooshy to display all the targets the user enabled.

**Comment by godbout** [comment] 2022-08-23 15:44
> Wow, thanks for the effort! What about moving the cursor to unhide the dock? (Not sure if that’ll even work…) Then move it back if Wooshy doesn’t execute a click.

super messy. you'd need Wooshy to move the mouse, wait for the Dock to show and finish its "transition", then ping all the elements again. and, as said above, there's no way to know when the transition is finished and you can finally ping again the final UI Element positions.

> And it does seems reasonable that if the user has checked the Dock button that the dock be always shown when Wooshy is invoked.

i didn't mean when it's invoked, i meant ALL THE TIME. like if you've checked the Dock in the Search Scope, then BOOM your Dock is always ON.

> When Wooshy does force the dock to be visible, defer the scanning and display of Dock targets until the Dock is visible. I mean, if the user has the Dock option turned on, it seems reasonable to slow down Wooshy to display all the targets the user enabled.

again, as said above, this is not doable. there is no way to know when the Dock finished showing. hence the issue.

the only two ways i can think of now are 1) always show the Dock if you check the option for the Dock in the Search Scope 2) enforce the Dock to show instantly. that works, but that means that it's changed for the whole system, all the time. not just when Wooshy is invoked. video coming.

**Comment by godbout** [comment] 2022-08-23 15:51
https://user-images.githubusercontent.com/121373/186203558-83eda58a-7d96-4d32-9c32-5c1473748c04.mp4

**Comment by godbout** [comment] 2022-08-23 16:04
still creates problems in fullscreen too, as the Dock may not be shown. but Wooshy currently would try to get items from the Dock. so again we could basically change the users' macOS settings, which kinda suck i think.

**Comment by godbout** [comment] 2022-08-23 16:05
but what i liked about the idea was that you could target minimized windows. maybe i should add this to [Wooshy: Window to the Foreground!](https://github.com/godbout/WooshyWindowToTheForeground) instead.

**Comment by blackketter** [comment] 2022-08-23 16:12
Yeah, I gotcha.

Jeez, it seems like it might not be worth the effort of trying to control the dock at all.

I think the current behavior is quite reasonable:  If the dock is visible, show the targets.  If not, don’t.  

Thanks for the effort exploring this, but the dock doesn’t really want to be tamed.

**Comment by godbout** [comment] 2022-08-23 16:15
yeah no worries. i didn't have any idea of what was possible or not so i had to scratch my own itch 😂️
now i'm gonna need some digestion time and see if my brains come up with something. that does look pretty slick tbh when the Dock shows up when you activate Wooshy 😅️ thanks for the idea.

**Comment by godbout** [comment] 2022-08-23 17:00
> If the dock is visible, show the targets. If not, don’t. 

question then: why adding the Dock in the Search Scope at all, if it's hidden anyways?

**Comment by blackketter** [comment] 2022-08-23 17:32
> On 2022-08-23, at 10:00am, G. ***@***.***> wrote:
> 
> 
> If the dock is visible, show the targets. If not, don’t.
> 
> question then: why adding the Dock in the Search Scope at all, if it's hidden anyways?
> 
> 

I think if the Dock is visible, then you should be able to search on its contents, see them highlighted and trigger them.

If the Dock isn’t visible, then there’s no reason to have them in the search scope at all, since you can’t trigger them.

Do I understand your question right?

**Comment by godbout** [comment] 2022-08-24 04:31
> On 2022-08-23, at 10:00am, G. ***@***.***> wrote: If the dock is visible, show the targets. If not, don’t. question then: why adding the Dock in the Search Scope at all, if it's hidden anyways?
> I think if the Dock is visible, then you should be able to search on its contents, see them highlighted and trigger them. If the Dock isn’t visible, then there’s no reason to have them in the search scope at all, since you can’t trigger them. Do I understand your question right?

my question was just plain dumb 😂️ my point was why would someone voluntarily tick the Dock checkbox in the Settings if their Dock is hidden anyways. but ultimately it doesn't matter. as you reported, Wooshy just has to handle the case better.

so now i just have to decide what's the best way to go forward:
1. highlight when Dock shown, ignore otherwise
2. warn the user when they check the option if their Dock is in autohide and/or hide in fullscreen, and give them the option to make Wooshy override those settings
3. warn the user when they check the option if their Dock is in autohide, and give them the option to make Wooshy change the delay and transition time + change setting of showing the Dock even when in fullscreen

**Comment by blackketter** [comment] 2022-08-24 05:11
> On 2022-08-23, at 9:31pm, G. ***@***.***> wrote:
> so now i just have to decide what's the best way to go forward:
> 
> highlight when Dock shown, ignore otherwise
> warn the user when they check the option if their Dock is in autohide and/or hide in fullscreen, and give them the option to make Wooshy override those settings
> warn the user when they check the option if their Dock is in autohide, and give them the option to make Wooshy change the delay and transition time + change setting of showing the Dock even when in fullscreen

Less is more.

I’d go with #1 for now and see if you get complaints/support requests.  You might learn something from this feedback that helps find an even better solution.

**Comment by godbout** [comment] 2022-08-24 16:58
i guess yeah, 1 is better than the current situation. 
but hiding and showing the Dock was pretty fucking cool.

**Comment by blackketter** [comment] 2022-08-24 17:57
Something occurred to me last night:

What if Wooshy were to continually scan for targets and redraw new and changed highlights while it was activated?  

If and when the dock was displayed the target would appear.  This would also have the possible benefit of updating targets based on changes to the contents of the window, menu bar icons, etc...

**Comment by godbout** [comment] 2022-08-27 15:59
so, a20 (https://github.com/godbout/Wooshy.docs/releases/tag/1.a20) comes with ignoring the Dock if it's hidden.

BUT. you're still probably going to have issues in your case. the issue is that i still haven't dug into the multiple monitor setup, and even less in your case of the active spaces being merged together (or whatever the option is). it's a big piece that's gonna require a lot of research, but that'll come.

also, the Dock is supposedly shown on what Apple calls the "first screen", which is different from the "main screen" which where the focus currently is. now, guess what, if you set your Dock to appear on the left, it may or may not appear on the "first screen". same for the right. only follows their doc if it's at the bottom. so if you're more of a left/right kinda guy, you're gonna have even more problems currently 😬️

**Comment by godbout** [comment] 2022-08-27 16:01
so i'm closing for now, and will link it into the multiple monitor issue. thanks for the idea, that was a great one actually.

**Comment by blackketter** [comment] 2022-08-27 16:05
Hm, just upgraded to 1.a20 and wooshy no longer highlights the dock items if auto-hiding is turned on but the dock is in view (cursor moved over it).

This did work in a19.  This is with a single display, dock to the right.

**Comment by godbout** [comment] 2022-08-27 16:23
ok, see video below:

https://user-images.githubusercontent.com/121373/187038863-7f42e5b3-ef11-4033-b57a-0cf4f93c4cb4.mp4

1. if Dock is hidden, UI Elements are not pinged
2. if Dock is show, UI Elements are pinged

i didn't think of testing your case because i don't understand the thought process behind. you use the mouse/trackpad to go to the Dock so that it shows, and THEN you activate Wooshy? then why not just clicking the Dock if you've already moved the mouse there?

the way to check if the Dock is visible or not is hacky. there's no proper Dock API. seems that when it's set in auto-hide, my hacky way may not work then (basically Apple says nope, there's no Dock there). i guess i can have a look on how to solve this case, but i still don't understand what you're trying to do.

**Comment by blackketter** [comment] 2022-08-27 16:32
Yeah, it’s an edge case.  Not really that useful, but I thought you’d like to know that the behavior changed.

**Comment by godbout** [comment] 2022-08-27 16:41
ah i see. thanks for reporting.

tools like Wooshy are kinda abusing APIs, rather than using them to do what they're supposed to. so it's always a thin line to find between consistency, and usefulness. in the case you're mentioning, yeah, i don't think it's a big deal. in day to day life i don't see how this case would show up, except just to test the app. although maybe i'm wrong. if there's good arguments that'd help. but in any case i'll check if there's a better way (and also not slower) to handle this.

**Comment by godbout** [comment] 2022-08-28 05:46
so i got something better, but...

https://user-images.githubusercontent.com/121373/187059598-a6e65bdd-3a8d-4795-9ede-c5a98a477840.mp4

you could now grab the Targets when you hover over the Dock. BUT. if like me you have the magnify on and some Targets are out of the screen, Wooshy would still grab them, while they're not clickable. so that's another issue. like said, it's a non-stop hell 😂️

**Comment by godbout** [comment] 2022-09-07 07:47
improved in a21: https://github.com/godbout/Wooshy.docs/releases/tag/1.a21

you can now target Dock elements when you get close to it and the Dock shows.

**Comment by godbout** [comment] 2022-09-07 07:48
there's still a case where it doesn't work "well". like when you use the Magnifier option and the icons are out of view. but i'm gonna be ok for now. closing this one.

**Closed by godbout** 2022-09-07 07:48 UTC
Labels: will do

**Comment by godbout** [comment] 2022-10-11 14:35
> Yeah, it’s not a big deal. I think the main motivation is consistency, that is, if there’s an item visible on the screen Wooshy should try to make it a target.

yes, you were right. thanks for reporting that.

> The auto-show-the-dock feature would be a clever hack to make more things visible on the screen. :)

there's some bad hacks that can be done. and it seems there's an app like Vimac that is doing so. not sure yet if i'll bother with Wooshy. you need to kill the Dock etc. makes the whole thing blink. kinda disgusting.
