### ISSUE TITLE
Feature request: Smart case

### ISSUE THREAD

**Issue by jannis-baum** [godbout/Wooshy.docs#61] opened 2022-08-21 16:23 UTC
> Like the `smartcase` option in Vim

Currently, queries in Wooshy are matched completely in-case-sensitively, i.e. `Search` matches `search`, `Search`, `SEARCH` and so on. Vim (among other tools such as [ripgrep](https://github.com/BurntSushi/ripgrep)) offer the option *smart case*, where queries that are all lower case are matched in-case-sensitively like Wooshy does at the moment, but queries that include at least one upper case character are matched case-sensitively. This means `search` will still match `search`, `SEARCH`, and so on, but `Search` will only match `Search` in its exact casing.

From what I've seen, it's very common to find `set smartcase` in people's `vimrc`'s, so this (at least to me) seems to be quite popular. I also feel like it could significantly cut down on the number of characters we have to type to get the match that we want in Wooshy, since the first letter of buttons is often capitalized.

For more reference, see `:help smartcase` in Vim or [options commonly used in ripgrep](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#common-options).

**Comment by godbout** [comment] 2022-08-22 07:50
ha! i didn't know about `smarcase`. nice. thanks for the idea, that's a great one.

many users have been asking for their own flavor of `Fuzzy Matching`. i think what i'm gonna do at a later stage is add something like for The Input's UI: Fuzzy Matching à la Alfred; Fuzzy Matching Launchbar, etc. i could add the `smartcase` in the Wooshy one.

probably i can add this as an option at first. shouldn't be hard. just need to spend some time on refactoring the tests. i like it thanks!

**Comment by godbout** [comment] 2022-08-23 17:22
i want to add this soon coz i think it's gonna be very useful.

i'm trying to see what do i do at first. do i add it without an option? do i add an option? what about later when i do the presets? would it still be an option? or included in the presets?

so quick question for you, regarding presets and fuzzy matching, what's your take? what do you use? what would you prefer? do you wanna become Wooshy's co-author?

**Comment by jannis-baum** [comment] 2022-08-24 08:44
> do i add it without an option? do i add an option? what about later when i do the presets? would it still be an option? or included in the presets?

I have two sides of looking at it:

1. *smart case* is something I've seen in a lot of places (like Vim and ripgrep for example) and often times it is an option and disabled by default. This seems to be the more conventional way of doing it (especially with tools that have been around for a long time), even though I'd go as far as to say most people that know about smart case will enable it in their configs.
2. I like sensible (*modern*?) convention over configuration. [fzf](https://github.com/junegunn/fzf), another tool that has it, has it enabled by default. If it was enabled by default, I'd say people going "Oh, that's cool" will be way more common than people being bothered by it. After all, it will only bother people searching `lIkE tHiS` or that have a stuck caps-lock key and people that want case-sensitive lower case matching, but it might be fair to assume these are edge cases?

So in the spirit of *"it just works"* and Wooshy being a macOS app, I would have it enabled by default and give an option to turn it off once you get to the options. This option might be a three-way switch between case-sensitive, case-insensitive and smart case; that's also what you see in the tools I mentioned.

> do you wanna become Wooshy's co-author?

Do you want to elaborate?🙈 You can also message me on [Telegram](https://t.me/jannisbaum).

**Comment by godbout** [comment] 2022-08-24 12:36
> So in the spirit of _"it just works"_ and Wooshy being a macOS app, I would have it enabled by default and give an option to turn it off once you get to the options. This option might be a three-way switch between case-sensitive, case-insensitive and smart case; that's also what you see in the tools I mentioned.

great. that's **exactly** what i had in mind. will implement soon.

> Do you want to elaborate?🙈 You can also message me on [Telegram](https://t.me/jannisbaum).

ah fuck i was just teasing sorry 😂️ coz you've been sending lots of great ideas, and i pick your brains so much that it feels kV/Wooshy are a bit yours too (and Aaron's). guess i have to stop with that joke (he was a victim too ☹️). (but internally i'm gonna start building a list of people to work with when the time comes... 👀️)

**Comment by godbout** [comment] 2022-08-24 16:22
done in a19: https://github.com/godbout/Wooshy.docs/releases/tag/1.a19

but i foresee some support. video incoming.

**Comment by godbout** [comment] 2022-08-24 16:37
https://user-images.githubusercontent.com/121373/186471819-ac304169-8741-4c31-a85f-66a690e51b06.mp4

there's several reasons for this happening:
1. Wooshy "combines" UI Elements. for example, for a button, you may have several UI Elements within (other buttons, static texts, etc.). that creates a lot of noise. so once the match is sone, Wooshy filters out UI Elements that are polluting, leaving only the ones that it makes sense to click. there's quite a complicated set of rules to get the set of Targets clean.
2. Wooshy combines all the UI Elements attributes and matches against that result. i guess a better way could be to apply the case setting only to what's visible on the screen? (not even make sure that could make sense.) another issue then is finding out what is visible on the screen. as far i can see till now, different UI Element types show different attributes (e.g. for buttons it's the title, for links it's the value) which means i'd have to differentiate every UI Element. and that would work only if the same Element type always uses the same attributes. not sure that's even the case, even less with custom stuff like webpages and Electron shit apps.

**Comment by godbout** [comment] 2022-08-24 16:41
i've been playing around with `Smart Case` with Wooshy and i find it much less useful than i thought, because of the issues mentioned above. it's actually more confusing to me.

see for yourself and let me know what's your experience. i'm reserving the right to drop it at a later stage if i keep feeling that this makes Wooshy worse at the end 😬️

**Comment by godbout** [comment] 2022-08-24 16:56
i think the case option ultimately kinda implies that you know exactly all the matching terms related to a UI Element, but that's not the case. there's a lot of metadata behind the scenes. so i'm really wondering if it's a good idea at the end. hopefully you can argue your case 😅️ after an hour of usage, not that convinced here.

**Comment by jannis-baum** [comment] 2022-08-24 17:22
Oh wow, I didn't realize this... but of course it's not as simple as searching for the things we see ^^ I've been using it for about 10 minutes now and I still feel like it helps. It seems to work how I would have expected in a lot of cases. But I can definitely see people getting extra confused about it in the other cases, which is a strong argument for removing it. I know would get confused if I didn't know the background information.

As long as there's no way to also search exactly what is displayed (which you explained why there isn't) I guess this might not be a good thing to have... at least not without a big disclaimer/explanation, but of course that's not desirable. Maybe you can keep it around but only as some secret easter-egg like having it unlock when we type "SOMEWHAT-SMART CASE" into the Wooshy preference pane? lol

But yeah, jokes aside, if it's not possible/feasible to (also) search exactly what we see, I understand scratching this for now :(

---

> Sent with helpful Wooshy smart case query `Comment`

**Comment by godbout** [comment] 2022-08-24 17:31
> Oh wow, I didn't realize this...

yeah. that's why i think twice when people ask stuff. it is ALWAYS a rabbit hole with a lots of unforeseen scary carrots.

> some secret easter-egg like having it unlock when we type "SOMEWHAT-SMART CASE" into the Wooshy preference pane? lol

what about when they use RoLlErCoAsTeR cAse? aww

> But yeah, jokes aside, if it's not possible/feasible to (also) search exactly what we see, I understand scratching this for now :(

hmm thinking about it, currently i've set the `Smart Case` as default, but i could (probably _should_) revert to `Case Insensitive` by default, so only the ones who understand a bit more may go for the `Smart Case`? might be a solution.

**Comment by godbout** [comment] 2022-08-24 17:32
> As long as there's no way to also search exactly what is displayed (which you explained why there isn't)

actually there was in the first alphas. lemme check the code.

**Comment by godbout** [comment] 2022-08-24 17:40
> actually there was in the first alphas. lemme check the code.

so in the first alphas there were something called the _narrowers_ with which you could, well, narrow your search. like:
1. ^ to match only what starts with the search term: `hey ^` would match `hey how are you`
2. $ to match only what ends with the search term: `hey $` would match `how are you hey`
3. ! to match exactly the search term: `hey !` would match `hey`

the way it worked in those special cases is rather than combining all the attributes, i would check independently for the title, label, and value, which should cover mostly what is seen on the screen.

maybe that could do it for the `Smart Case`? but thinking a bit more, we'll get the same issue with the `Case Sensitive`. and thinking a bit more more, then by doing this you lose one of the great feature of Wooshy which is always matching against the metadata...

**Comment by godbout** [comment] 2022-08-24 17:49
fuck this is even worse than i thought:

https://user-images.githubusercontent.com/121373/186488235-41776310-3a55-484e-a515-7c2f5cf28c50.mp4

and this is not the issue about matching against all the attributes, in this case this is the issue than Wooshy matches against the link (that contains a `C` rather than a `c`) rather than all the links' children elements (static text etc.).

**Comment by jannis-baum** [comment] 2022-08-24 17:49
> the way it worked in those special cases is rather than combining all the attributes, i would check independently for the title, label, and value, which should cover mostly what is seen on the screen.
> 
> maybe that could do it for the Smart Case? but thinking a bit more, we'll get the same issue with the Case Sensitive. and thinking a bit more more, then by doing this you lose one of the great feature of Wooshy which is always matching against the metadata...

I'm not sure I understand this part... Why is checking title, label and value mutually exclusive with checking the metadata? What's *the metadata*? The way I thought Wooshy worked was that all of those are checked (or even just concatenated) anyways and as soon as some substring matches (in whatever casing rule), Wooshy has a match. How does it work?

**Comment by godbout** [comment] 2022-08-24 17:56
> I'm not sure I understand this part... Why is checking title, label and value mutually exclusive with checking the metadata? What's _the metadata_? The way I thought Wooshy worked was that all of those are checked (or even just concatenated) anyways and as soon as some substring matches (in whatever casing rule), Wooshy has a match. How does it work?

at first yes, it was just about all the attributes getting concatenated, and matching against that.
then i added the _narrowers_, so i needed to match against attributes individually. it made sense for title, label and value because those are what you see on the screen. it doesn't make sense to use a _narrower_ against some metadata that you cannot see (value descriptor, role descriptor, subrole, help, placeholder etc. etc.). so, to keep things speedy, if you used a _narrower_, i would only check what's visible on the screen and ignore the rest of the metadata. somehow it does make a bit of sense for the `case sensitivity` too, because why would you want it on text that you cannot see?

**Comment by godbout** [comment] 2022-08-26 08:59
> and this is not the issue about matching against all the attributes, in this case this is the issue than Wooshy matches against the link (that contains a `C` rather than a `c`) rather than all the links' children elements (static text etc.).

ok so i was trying to think more about this and reaching the bottom of the problem, and this is even worse than when i thought it was worse than i thought 😂️ (but at least we're closer to reality, and i have a decision)

so i thought, ok, maybe rather than merging some elements like links with their children, i can ignore the parents (link) and target the children instead (static text). i decided not to do that in the past because i find it uglier and less intuitive for the end user. see below.

merging so that the user can see and target the link:

<img width="563" alt="parents" src="https://user-images.githubusercontent.com/121373/186867087-f889a5b7-66ed-4e62-a4b8-c027cb2f5cd4.png">

not merging, displaying the children, and removing the parent:

<img width="563" alt="children" src="https://user-images.githubusercontent.com/121373/186867186-59d8e79f-a59f-4fae-b603-d70c3a78fdb7.png">

but the issue is even with this, you can't solve our problem. for example, in GitHub, the **Starred**:

<img width="563" alt="Screenshot 2022-08-26 at 16 51 58" src="https://user-images.githubusercontent.com/121373/186867330-391f8676-769d-4c21-a3ff-e6ea08e361e4.png">

with both methods, the **Starred** is never reachable. the reason? this is a webpage, so it's custom shit, and the **Starred** is nowhere within an AX UI Element.

so for the end user, it's already a little bit confusing. if you add the `Smart Case` (or any kind of case for that matter), the whole UX makes even less sense. personally trying to use the `Smart Case` or the `Sensitive` and most of the time it doesn't act the way i want.

so i'm really considering dropping it in the next release. the search will be one day improved though through different `Fuzzy Matching` presets. (at least à la Alfred and Launchbar.)

**Comment by godbout** [comment] 2022-08-27 15:52
removed ☹️ https://github.com/godbout/Wooshy.docs/releases/tag/1.a20

i don't see a good way to do this, sorry.

**Comment by godbout** [comment] 2022-08-27 16:03
closing for now. please reopen if you have any other idea or you have some good arguments 😅️

**Closed by godbout** 2022-08-27 16:03 UTC
Labels: will do
