### ISSUE TITLE
App interferes with Dock hiding

### ISSUE THREAD

**Issue by dhnaranjo** [godbout/Wooshy.docs#132] opened 2023-08-18 17:23 UTC
Yowhattup? Wooshy causes the Dock to intermittently not hide when you move the cursor away from it. The issue goes away when Wooshy is closed. Below is a gif screencast demonstrating the issue. No other application is running at this time.

Sequence is:
- Launch Wooshy
- Demonstrate issue
- Quit Wooshy
- Fail to cause issue
- Launch Wooshy
- Demonstrate issue
![Screen Recording 2023-08-18 at 12 12 30 PM](https://github.com/godbout/Wooshy.docs/assets/536280/17e31bd0-3f8d-446c-a8c4-215ff91c8c72)

**Comment by godbout** [comment] 2023-08-18 18:21
wait wtf. how the fuck did you find this 😂️😂️😂️

i thought it was a macOS bug actually, that the Dock would sometimes gets stuck. but i can reproduce. wth. also, is it that the Dock shows up faster when you have Wooshy running? it's weird coz i don't remember doing anything special on it. will investigate. thanks!

**Comment by dhnaranjo** [comment] 2023-08-18 19:00
Oh, this might be useful for you, I got the idea to hunt through my background apps from this StackExchange post: https://apple.stackexchange.com/questions/455059/dock-hiding-gets-stuck-how-to-fix, where the issue was attributed to Parallels Toolbox.

**Comment by godbout** [comment] 2023-08-18 19:04
nice. thanks. well obviously it seems pretty clear to me that one is related to Wooshy. gonna have to start commenting coz really, not sure what's going on here.

**Comment by godbout** [comment] 2023-08-18 19:12
ok so it's my event tap tracking mouse movement that's somehow doing this. but it's standard stuff, hmm. gonna be fun. maybe some FB reports to Apple. will keep you updated. more investigation needed!

**Comment by godbout** [comment] 2023-08-18 20:31
i can solve this by changing where in the event steam i'm putting my event tap, but that will create issues with some other apps, including my other app [kindaVim](https://github.com/godbout/kindaVim.docs). so i'm not sure yet if this is worth solving tbh. it's a bit technical but there's only 6 places in the event stream where you can put a tap, and depending where you put it you start having issues with other apps that also use event taps, like Alfred, Karabiner-Element, Hammerspoon etc. so yeah, not sure i wanna fix this and break other stuff. will still investigate more deeply tho.

**Comment by dhnaranjo** [comment] 2023-08-18 22:07
I'm not gonna lie Wooshy is cool but it does not bring me more joy than this bug brings me frustration, and in my opinion it would be a disservice to your customers to cause what appears to be an OS bug that they can't resolve and is not obviously linked to your app. Like you said, how the fuck did I find it?

**Comment by godbout** [comment] 2023-08-19 07:20
> I'm not gonna lie Wooshy is cool but it does not bring me more joy than this bug brings me frustration

seems Wooshy is not that useful to you then 🤣️🤣️🤣️

> and in my opinion it would be a disservice to your customers to cause what appears to be an OS bug that they can't resolve and is not obviously linked to your app. Like you said, how the fuck did I find it?

yeah, of course i'm gonna try to find a way around that. here's the usual process: 1. build a project that shows the bug 2. report to Apple 3. find ways around the bug. you kinda hope that point 2 will be resolved by Apple but in my experience it rarely, rarely happens.

so yeah, i'm gonna do all i can to avoid this, but it's gonna be more tricky stuff that shouldn't be there in the first place, waiting/hoping for Apple to fix their stuff. the issue is doing those tricky stuff usually come with side effects. so, wait and see. as said, more investigation needed here for now.

**Comment by godbout** [comment] 2023-08-19 07:22
btw, just curious. how do you use your Dock? why do you go there? personally i open all my stuff through Alfred so it never bothered me enough so that i dig into the issue. (thought it was a macOS bug at first, not related to Wooshy.)

**Comment by godbout** [comment] 2023-08-19 07:49
this bug was reported to Apple in... 2011 🤣️: http://www.openradar.me/10185068

**Comment by godbout** [comment] 2023-08-19 08:08
reported to Apple as FB13006563.
showcase project: https://github.com/godbout/EventTapDockIssue
followup: https://github.com/feedback-assistant/reports/issues/416

**Comment by jannis-baum** [comment] 2023-08-19 16:54
I was wondering why I have never had this issue even though I've been using Wooshy for quite some time and have always had my Dock set to auto-hide. Turns out the issue disappears when you set the hiding animation time & delay to 0

```sh
# remove the auto-hiding dock delay
defaults write com.apple.dock autohide-delay -float 0
# remove the animation when hiding/showing the dock
defaults write com.apple.dock autohide-time-modifier -float 0
```

which in my opinion is much better anyways. Just in case this helps and/or tips the scales back in Wooshy's favor for you @dhnaranjo 😁

**Comment by dhnaranjo** [comment] 2023-08-19 17:31
> seems Wooshy is not that useful to you then

@godbout nah it's great but I would rather eliminate a frustration than gain a benefit, and can limp by with like vimperator or whatever. Repeat annoyance accumulates, you know?

As for the dock, I minimize stuff to it pretty often. I do use raycast for launching.

@jannis-baum your fix is perfect, thank you.

**Comment by godbout** [comment] 2023-08-19 18:27
> I was wondering why I have never had this issue even though I've been using Wooshy for quite some time and have always had my Dock set to auto-hide. Turns out the issue disappears when you set the hiding animation time & delay to 0
> 
> ```shell
> # remove the auto-hiding dock delay
> defaults write com.apple.dock autohide-delay -float 0
> # remove the animation when hiding/showing the dock
> defaults write com.apple.dock autohide-time-modifier -float 0
> ```
> 
> which in my opinion is much better anyways. Just in case this helps and/or tips the scales back in Wooshy's favor for you @dhnaranjo 😁
> 
> Edit: if you try this out, make sure to restart your Dock after adjusting the preferences, e.g. with `killall Dock`

!!! that explains. used to have that on my previous machines, and before my MBP died some weeks ago. still, gonna have to fix it for all the others 😅️

**Comment by godbout** [comment] 2023-08-19 18:29
> Repeat annoyance accumulates, you know?

well i guess you're not gonna like the popup that asks you to rate the app and write a review... (kidding)

**Comment by godbout** [comment] 2023-08-20 07:13
<img width="817" alt="Screenshot 2023-08-20 at 15 13 07" src="https://github.com/godbout/Wooshy.docs/assets/121373/7c1e9321-3faa-4571-acb1-723eb33c30df">

took me a while this morning (1pm) to realize that this was not about "dog shit" 😂️😂️😂️

**Comment by godbout** [comment] 2023-09-04 18:58
fixed in Ws13: https://github.com/godbout/Wooshy.docs/releases/tag/13

**Closed by godbout** 2023-09-04 18:58 UTC
