### ISSUE TITLE
In MailMate, Wooshy preforms a click and ctrl click when ctrl clicking the From email

### ISSUE THREAD

**Issue by aaronrolls** [godbout/Wooshy.docs#67] opened 2022-08-28 01:25 UTC
When ctrl clicking this section with Wooshy, Wooshy will preform a click, then a ctrl click.

<img width="483" alt="CleanShot2022-08-28at13 21 55@2x" src="https://user-images.githubusercontent.com/47949221/187053632-89a568df-3d64-444b-a73d-ee5fc90ae79b.png">

Ctrl clicking with a mouse does not have this issue. Likewise the Accessibility Inspector works as intended.

**Comment by godbout** [comment] 2022-08-28 05:15
i deleted MailMate yesterday 😂️
will check. although weird that it happens only in that situation.

**Comment by godbout** [comment] 2022-08-29 13:48
can reproduce.

**Comment by godbout** [comment] 2022-08-29 14:01
i'm having the same behavior most of the time (but not all the time) when using the normal `ctrl click`. not you?

https://user-images.githubusercontent.com/121373/187218936-34657f36-b8ee-4828-9d59-ca2dccb9411a.mp4

**Comment by aaronrolls** [comment] 2022-08-29 20:30
Nope, I don't have the same issue with control click. It only ever brews up the menu

**Comment by godbout** [comment] 2022-08-30 04:44
> Nope, I don't have the same issue with control click. It only ever brings up the menu

just to be extra sure, you're doing literally a `control click` right? not a `right click`. i don't have issue with mouse `right click` or trackpad `two fingers`, but i have issue with `control click` without Wooshy running.

**Comment by aaronrolls** [comment] 2022-08-30 04:47
Hahaha, yeah, I'm doing an actual `control click`. I'm pretty sure I don't have any app remapping control click to right click.

**Comment by aaronrolls** [comment] 2022-08-30 04:48
This is the version I am using.

<img width="294" alt="CleanShot2022-08-30at16 47 59@2x" src="https://user-images.githubusercontent.com/47949221/187351501-8ce946cf-ec96-49e9-b1ff-eac9b11bff34.png">

**Comment by godbout** [comment] 2022-08-30 05:05
in my case. first three clicks are `right click`, works fine. three next are `control click`, the two first fail.

https://user-images.githubusercontent.com/121373/187351440-5a5761c3-d465-4356-a8af-3ea0b26e7dde.mp4

**Comment by godbout** [comment] 2022-08-30 05:06
> Hahaha, yeah, I'm doing an actual `control click`. I'm pretty sure I don't have any app remapping control click to right click.

could it be related that you guys live upside down?

**Comment by godbout** [comment] 2022-08-30 05:07
> This is the version I am using.
> 
> <img alt="CleanShot2022-08-30at16 47 59@2x" width="294" src="https://user-images.githubusercontent.com/47949221/187351501-8ce946cf-ec96-49e9-b1ff-eac9b11bff34.png">

Version 1.14 (5895) here but i don't think that should be the problem.

**Comment by aaronrolls** [comment] 2022-08-30 06:21
> could it be related that you guys live upside down?

Probably, everything "just works" down here.

> in my case. first three clicks are right click, works fine. three next are control click, the two first fail.

I can't get it to produce the issue you are having unfortunately. It works every time for me.

**Comment by godbout** [comment] 2022-08-30 06:25
> Probably, everything "just works" down here.

i guess you meant "sʞɹoʍ ʇsnɾ".

> I can't get it to produce the issue you are having unfortunately. It works every time for me.

i was trying to get coffee peacefully here so i'm on a trackpad. i'll try at home with a mouse.

**Comment by godbout** [comment] 2022-08-30 07:45
interesting. so:

1. i cannot reproduce neither here with a mouse
2. if i force click on the trackpad, the issue doesn't happen

it seems to be happening with:
1. trackpad set to light touch. like you don't really press, just touch it to generate a click
2. Wooshy

**Comment by godbout** [comment] 2022-09-03 17:13
handling the `control click/right click` differently for 21. the issue will be gone.

**Comment by godbout** [comment] 2022-09-07 07:45
fixed in a21: https://github.com/godbout/Wooshy.docs/releases/tag/1.a21
thanks.

**Closed by godbout** 2022-09-07 07:45 UTC
