### ISSUE TITLE
not working on Warp

### ISSUE THREAD

**Issue by roelvangils** [godbout/Wooshy.docs#21] opened 2022-07-26 22:50 UTC
Nope

**Comment by godbout** [comment] 2022-07-27 03:22
🤔️

![Screenshot 2022-07-27 at 11 21 48](https://user-images.githubusercontent.com/121373/181153722-04083b85-2ff4-4027-a7ce-af9b5f94634e.png)

**Comment by godbout** [comment] 2022-07-27 03:24
but yeah. basically Warp is not accessible at all:

https://user-images.githubusercontent.com/121373/181153921-8a590f04-79ff-4bd4-9b31-3e24bbf7eaf0.mp4

which means we can't grab any info from it. no tool will work.

i'll ping the devs and ask if they can make it accessible. probably they won't else they would have done it. most probably the issue is with the technology they're using. but once i ask, it's in their hands. closing for now. will update when i send them an email.

**Closed by godbout** 2022-07-27 03:24 UTC

**Comment by godbout** [comment] 2022-07-27 07:01
regarding Warp and the macOS Accessibility: https://docs.warp.dev/features/accessibility
https://github.com/warpdotdev/Warp/issues/901

so, nothing can be done now.
