### ISSUE TITLE
Bug: Search boxes don't show on fullscreen apps on second monitor

### ISSUE THREAD

**Issue by h-spiess** [godbout/Wooshy.docs#128] opened 2023-08-02 08:48 UTC
Hey,

First, I really like your app. But I have encountered a weird bug. When one search in fullscreen apps on the secondary monitor the search boxes don't show up but the elements can be activated (without knowing which will be selected if multiple elements match the search).

Search boxes appear on the second monitor in non-full screen apps and search boxes appear on the primary monitor in fullscreen apps. It's just the above mentioned combination that does not work.

I hope the description helps. I'm on the newest version of Wooshy and the newest version of macOS Ventura 13.5 with M1 chip (if that matters).

Best,
Heiner

**Comment by godbout** [comment] 2023-08-16 15:22
i'm not able to reproduce. see below.

https://github.com/godbout/Wooshy.docs/assets/121373/d628c11b-840f-4f86-999a-c70e8e5495a9

so can you let me know a couple of things:
1. your Wooshy Settings. can you screenshot that?
2. the position of your displays towards each other. i have automated tests for all positions (first screen above, below, second on the left, right, etc. etc.) but who knows.
3. the color of the contour of your monitor, and the name of the employee who sold it to you (joke. just in case)

thanks.

**Comment by godbout** [comment] 2023-08-16 15:22
also, would it be possible that it's an issue with which app is focused? Wooshy can only grab the UI Elements from the currently focused app. (because that's how the macOS API works.)

**Comment by godbout** [comment] 2024-12-08 06:01
no answer. closing.

**Closed by godbout** 2024-12-08 06:01 UTC
