### ISSUE TITLE
Weird bug with safari and accessibility information

### ISSUE THREAD

**Issue by aaronrolls** [godbout/Wooshy.docs#40] opened 2022-07-30 08:47 UTC
I have an interesting issue when loading web pages. Sometimes when going to a new site, the safari tab won't return accessibility information in the normal way for the website that it contains.

Wooshy will not return anything for the website until you switch to another tab then switch back. This might be a safari bug, but I don't have high hopes of apple fixing it so it would be nice if it could be worked around.

While Safari doesn't return accessibility info normally (I think) it does return it. Take a look at the video below.

[Video to big to host on Github, I'm not over compensating though...](https://www.youtube.com/watch?v=Mbnv6EpIJ-Q)

It is acting weird.

The easiest way to reproduce this issue is to open links from [google](google.com) and try to search with Wooshy. Can be a little random.

**Comment by godbout** [comment] 2022-07-30 14:46
> [Video to big to host on Github, I'm not over compensating though...](https://www.youtube.com/watch?v=Mbnv6EpIJ-Q)

no way i'm clicking that fucking link.

**Comment by godbout** [comment] 2022-07-30 14:51
ok i've clicked. too curious.

i've had some weird stuff with Safari too. like i have the boxes but the position are all wrong. the AX info returned by Safari is not correct. in my case nothing to do expect quitting and reopening. both Vimac, Homerow and Shortcat are affected (yeah, it's three, i know. how to say both for three? throth?) so pretty sure it's a bug in Safari. i will report. i've installed Ventura public beta 2 yesterday and i have another plethora of stuff to report. this is not going in a good direction 😂️

**Comment by aaronrolls** [comment] 2022-07-30 20:41
Currently I have created a shortcut via Keyboard Maestro to quickly switch to another tab and back again. That should carry me over. But I do plan to visit this issue again. All the info you need is still being received by the accessibility inspector `Value/Label` `Dimensions` & `Position` so it should be possible to work around the issue.

I'll have a think on it and see if I can come up with an idea.

**Comment by godbout** [comment] 2022-07-31 02:33
> But I do plan to visit this issue again.

yes. i will still investigate that one too. it may be different from the one i'm encountering where i need to quit Safari. how are Vimac etc. doing with that issue? working, or same as Ws?

> All the info you need is still being received by the accessibility inspector `Value/Label` `Dimensions` & `Position` so it should be possible to work around the issue.

i think also the Accessibility Inspector uses some private APIs to activate stuff, that some other apps can't do (easily). also may be a case where the AX info is not available when i ping it? not sure. will have to check later.

**Comment by godbout** [comment] 2022-07-31 10:01
i'm trying to reproduce to send a feedback to Apple but i can't. i want to check the Accessibility Inspector too.

**Comment by godbout** [comment] 2022-07-31 10:02
i'll probably wait that it happens randomly.

**Comment by aaronrolls** [comment] 2022-07-31 10:13
Hmmm… it happens quite frequently for me. Maybe I have an other app that is conflicting with safari.

I have: 
- Homerow
- Keyboard Maestro
- Karabiner Elements (for a super key)
- Alfred
- Wooshy
- KindaVim
- rcmd
- Rectangle
- I have others, but none that need accessibility

I’d reinstall safari but that would mean I’d need to reinstall MacOS….

**Comment by godbout** [comment] 2022-07-31 10:25
there's a report about Firefox working on and off and i'm starting to think that it may be an app disabling the AX special attribute for Firefox, that is needed in order to ping the AX. but in the case of Safari, it doesn't need an special attribute. so, i don't know.

i don't think reinstalling Safari/macOS would help. but maybe dropping a few apps, reboot and see if it changes anything?

**Comment by godbout** [comment] 2022-07-31 10:30
i was checking your video again. it's so nice. (the second one, not the first one.) when you hover with the Accessibility Info the first time, you don't get the green boxes. something is off not just with Wooshy. i haven't started yet the feature where you hover an item and it shows the AX data. that may use another API that does work. like the API seems to be about grabbing the AX info just for that element under the mouse position. you don't need to go through the AX tree. maybe when you have the issue, the AX tree is not accessible? no idea. i haven't got this at all.

**Comment by godbout** [comment] 2022-07-31 10:37
also, forgot if i asked. what's the result with Homerow? does it get the elements?

Vimac used to keep enabling/disabling the AX if i'm not wrong. maybe Homerow does the same and fucks up sometimes? although on Safari that shouldn't affect, but also the special AX attributes are buggy and break stuff (like window manager that don't deliberately do some tricks. Rectangle is one that is doing the trick). so maybe disable Homerow for a while and see? (haha trying to destroy the competition!)

**Comment by aaronrolls** [comment] 2022-07-31 18:19
Homerow is very similar. Most of the time it will not show anything like Wooshy does, rarely it will show phantom buttons that don't do anything while Wooshy shows nothing.

**Comment by godbout** [comment] 2024-12-22 11:54
@aaronrolls what about now? still having issues? if not can we close? thanks.

**Comment by godbout** [comment] 2024-12-31 07:05
no news. closing.

**Closed by godbout** 2024-12-31 07:05 UTC
